# Generated by Django 3.2.15 on 2024-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_question',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('question_title', models.CharField(max_length=50)),
                ('answer', models.TextField(max_length=1000)),
                ('Judge', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'answer_question',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('question', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
