# Generated by Django 3.2.15 on 2024-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_answer_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='Judge',
            field=models.BooleanField(default=False),
        ),
    ]
